spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/msa
    username: msa
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false  # Hibernate id 생성전략 수용 여부 - false 설정시 mysql에서 @GeneratedValue 값으로 IDENTITY가 선택된다.
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb
logging:
  level:
    org.hibernate.SQL: debug
